# Generated by Django 4.1 on 2022-08-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_card', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
